### ISSUE TITLE
P5js can't get the local file

### ISSUE THREAD

**Issue by yuanwu1454** [aferriss/p5jsShaderExamples#3]
Did you have this problem？ And how do you solve this? 

Fetch API cannot load file:///Users/entakeshi/Project/p5jsShaderExamples/1_basics/1-1_red/basic.vert. URL scheme must be "http" or "https" for CORS request.
The p5.js can't get this file. The local file must be http or https.

**Comment by nucliweb** [comment]
Hello @yuanwu1454 👋🏼

You need a web server to use HTTP protocol.

If you have installed Node in your system, you can use [serve](https://www.npmjs.com/package/serve) to run a web server easier.

If you need help, let me know 😊

**Comment by yuanwu1454** [comment]
thank you , man
