### ISSUE TITLE
Pass Text as Texture in Rectangle Shader Example

### ISSUE THREAD

**Issue by KonVas** [aferriss/p5jsShaderExamples#6]
Hello I have this example, but it seems it wasn't that easy to pass some changing text as texture on my rectangle. Example below:

`function draw() {
  background(0)
  noStroke()
  text(`Istanbul Coding Ensemble \n fps ${textDisplayer.scrollFrequency}`, -590, -355)
  text(`Code from: \n ${who}`, -590, -300)
  //textDisplayer.fadeout()
  textDisplayer.display()
  textDisplayer.rotate()
  myShader.setUniform('iceLogo', img)
  shader(myShader)
  translate(240, 0, 0)
  box(width / 12)
}
`

**Comment by aferriss** [comment]
Hi, Can you post your complete code example? Without seeing more I'm not sure I can help. In general what you can do if you want to use a shader on text is to render the text into a graphics layer. Here's a small example:

```
let sh;
let g;
function preload(){
  sh = loadShader("shader.vert", "shader.frag");
}

function setup(){
  createCanvas(512, 512, WEBGL);
  g = createGraphics(512, 512);
}

function draw(){
  g.clear();
  g.text("blah blah", 50, 100);

  shader(sh);
  sh.setUniform("tex0", g)
  rect(0, 0, width, height);
}
```

Going to close this for now but feel free to reopen if you need more help
